### ISSUE TITLE
使用docker-compose修改9443端口重启后，客户端连接不上

### ISSUE THREAD

**Issue by tongjiann** [xubiaolin/docker-zerotier-planet#193]
最开始用的9413端口，所有通过zerotier自建的planet的leaf速度是正常的，但是近期发现好像被限速了，然后就修改了docker-compose中的9413端口后重新启动，发现客户端一直提示REQUESTING_CONFIGURATION。这是什么原因导致的，有什么解决方案吗

难道重启容器后还要重新把客户端的数据给清掉，才能正常使用吗

服务器在阿里云
客户端是2个Mac
compose文件如下
```yml
version: '3'

services:
  myztplanet:
    image: xubiaolin/zerotier-planet:latest
    container_name: cusotom_planet
    ports:
      - 7893:7893
      - 7893:7893/udp
      - 3413:3413
      - 2900:2900
    environment:
      - IP_ADDR4=xxx.xxx.xxx.xxx
      - IP_ADDR6=
      - ZT_PORT=7893
      - API_PORT=3413
      - FILE_SERVER_PORT=2900
    volumes:
      - ./data/zerotier/dist:/app/dist
      - ./data/zerotier/ztncui:/app/ztncui
      - ./data/zerotier/one:/var/lib/zerotier-one
      - ./data/zerotier/config:/app/config
    restart: unless-stopped
```

Network信息如下
![Image](https://github.com/user-attachments/assets/4a1238f4-abb1-4cc4-b0cb-f3a935219e5e)

我使用nmap确认过，服务器的udp:7893/tcp:7893端口是通的
